# Generated by Django 5.2.3 on 2025-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_slug',
            field=models.SlugField(blank=True, verbose_name='Lecture Slug'),
        ),
    ]
